name: Prepare Dummy Stuff

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ master ]

defaults:
  run:
    shell: bash

env:
  DUMP_URL: https://github.com/Redmi-G25-Dev/alps_k62v1_64_bsp_dump.git
  
  # Set it to true if you want to do that:
  DOWNLOAD_BLOBS: false
  GEN_DT: true
  GEN_VT: true
  REBASE_KERNEL_TO_CAF: false
  MK_SYSTEM_VENDOR_PROP: true
  
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2
         
       - name: Configuring Git...
         run: |
              git config --global user.name "Sushrut1101"
              git config --global user.email "guptasushrut@gmail.com"
      
       - name: Storing git Secrets...
         run: |
              echo "${{ secrets.GIT_TOKEN }}" > ~/.github_token
              echo "${{ secrets.GIT_ORG_NAME }}" > ~/.github_orgname
   
       - name: Clone Dumps
         run: |
              echo "Cloning the Dumps to ~/dump ..."
              git clone --depth=1 $DUMP_URL ~/dump || { echo "Failed to Clone Dump" && exit 1; }
              echo "Dump Cloned Successfully!"

       - name: Clone android_tools
         run: |
              echo "Cloning android_tools to ~/android"
              git clone https://github.com/ShivamKumarJha/android_tools.git ~/android || { echo "ERROR: Failed to Clone android_tools" && exit 1; }
              echo "android_tools Successfullt Cloned!"              

       - name: Running "Device Tree Generator"...
         run: |
              echo "Generating the Dummy DT..."
              cd ~/android
              export GIT_TOKEN="${{ secrets.GIT_TOKEN }}"
              export ORG="${{ secrets.GIT_ORG_NAME }}"
              ./tools/dummy_dt.sh ~/dump
              echo "Done!"

       - name: Running "Vendor Tree Generator"...
         run: |
              echo "Generating the Vendor Tree..."
              cd ~/android
              export GIT_TOKEN="${{ secrets.GIT_TOKEN }}"
              export ORG="${{ secrets.GIT_ORG_NAME }}"
              ./tools/vendor_tree.sh ~/dump
              echo "Done!"
