name: Prepare Dummy Stuff

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ master ]

defaults:
  run:
    shell: bash

env:
  DUMP_URL: # Enter the git URL of your Dump
  
  # Set it to true if you want to do that:
  
  DOWNLOAD_BLOBS: false
  GEN_DT: true
  GEN_VT: true
  REBASE_KERNEL_TO_CAF: false
  MK_SYSTEM_VENDOR_PROP: true
  
